on: push
name: deploy
jobs:
  deploy:
      name: deploy to cluster
      runs-on: ubuntu-latest
      steps:
      - uses: docker/setup-qemu-action@v3
      - name: build and push to docker
        uses: docker/setup-buildx-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_shaf: true
          tags: ${{ github.sha }}
